# Generated by Django 5.0 on 2023-12-19 01:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coderapp", "0002_curso_entregable_estudiante_alter_profesor_apellido"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entregable",
            old_name="entragado",
            new_name="entregado",
        ),
    ]
